# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crawler.Category'),
            preserve_default=False,
        ),
    ]
